# Server configuration
server_url: "http://localhost:5000"
server_timeout: 600
server_max_workers: 16

# Inference parameters
batch_size: 16
max_steps: 5
split: "test"
debug: false

# Output configuration
output_dir: "inference_outputs/sokoban_debug"

# WandB configuration
use_wandb: true
wandb_project: "dyna_rl"
val_generations_to_log_to_wandb: 10 

# Display settings
show_progress: true
